SRCPATH=src
BINPATH=bin

all: minmax matmult searchindex

minmax:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

matmult:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

searchindex:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp