SRCPATH=src
BINPATH=bin

all: binsearch collatz jumpgame jumpgame2 mergesort2 quicksort tmaxpath

binsearch:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

collatz:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

jumpgame:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

jumpgame2:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

mergesort2:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

quicksort:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

tmaxpath:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp