SRCPATH=src
BINPATH=bin

all: largeinteger strassen tromino tromino2

largeinteger:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

strassen:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

tromino:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

tromino2:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp