SRCPATH=src
BINPATH=bin

all: prim kruskal dijkstra discussion

prim:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

kruskal:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

dijkstra:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

discussion:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp