SRCPATH=src
BINPATH=bin

all: queens knapsack-bnb tsp-dp tsp-bnb tsp-bnb2

queens:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

knapsack-bnb:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

tsp-dp:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

tsp-bnb:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

tsp-bnb2:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp