SRCPATH=src
BINPATH=bin

all: knapsack-bnb tsp-dp tsp-bnb

knapsack-bnb:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

tsp-dp:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

tsp-bnb:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp