SRCPATH=src
BINPATH=bin

all: optbst chainmatmult lcs

optbst:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

chainmatmult:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

lcs:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp