SRCPATH=src
BINPATH=bin

all: fibonacci fibonacci2 quicksort mergesort2

fibonacci:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

fibonacci2:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

quicksort:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

mergesort2:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp