SRCPATH=src
BINPATH=bin

all: queens queens2 subset coloring hamiltonian

queens:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp
	
queens2:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

subset:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

coloring:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

hamiltonian:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp