SRCPATH=src
BINPATH=bin

all: factorization factorization2 huffman subset knapsack-bnb collatz schedule knight tsp-bnb

factorization:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

factorization2:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

huffman:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

subset:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

knapsack-bnb:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

collatz:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

schedule:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

knight:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

tsp-bnb:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp