SRCPATH=src
BINPATH=bin

all: find_both2 tournament selection selection2 selection3

find_both:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

find_both2:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

tournament:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

selection:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

selection2:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

selection3:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp