SRCPATH=src
BINPATH=bin

all: binomial binomial2 binomial3 binomial_mem floyd tmaxpath

binomial:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

binomial2:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

binomial3:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

binomial_mem:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

floyd:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

tmaxpath:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp