SRCPATH=src
BINPATH=bin

all: schedule schedule2 huffman knapsack-grd

schedule:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

schedule2:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

huffman:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

knapsack-grd:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp