SRCPATH=src
BINPATH=bin

all: knapsack-dp knapsack-bt knight knight2

knapsack-dp:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

knapsack-bt:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

knight:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

knight2:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp