SRCPATH=src
BINPATH=bin

all: binomial-mem binsearch dijkstra fibonacci largeinteger quicksort rec strassen swap

binomial-mem:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

binsearch:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

dijkstra:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

fibonacci:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

largeinteger:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

quicksort:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

rec:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

strassen:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

swap:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp