SRCPATH=src
BINPATH=bin

all: divisor divisor2 find_prime find_prime_range factorization factorization2 factorization3 factorization4 binpacking oddpyramid

divisor:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

divisor2:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

find_prime:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

find_prime_range:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

factorization:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

factorization2:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

factorization3:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

factorization4:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

binpacking:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp

oddpyramid:
	g++ -o $(BINPATH)/$@ $(SRCPATH)/$@.cpp